# This is a basic workflow to help you get started with Actions

name: Linux Build

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
      - '.gitignore'
      - 'SRS.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
  pull_request:
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install node modules
        working-directory: ${{github.workspace}}
        run: npm install

      - name: Test Contracts
        working-directory: ${{github.workspace}}
        run: |
          npx hardhat test
